### ISSUE TITLE
Typescript - withHandler type error

### ISSUE THREAD

**Issue by alexandermckay** [TrueFit/bach#11]
I am getting a typescript warning that appears to be an error

Property 'X' does not exist on type 'Props | undefined'
I have recreated an example of the issue. Look specifically at the withHandlers object

I also created an issue [here](https://github.com/TrueFit/bach-recompose/issues/6#issue-645949117). The reason for the duplication is that I was uncertain if that repository is regularly checked.

**Comment by jgretz** [comment]
this is an issue in the bach-recompose library ... I will take care of it over there
