### ISSUE TITLE
No examples in the documentation or examples directory that use custom hooks

### ISSUE THREAD

**Issue by alexandermckay** [TrueFit/bach#12]
Hello, 

I was unable to find any examples that demonstrate how to use custom hooks with `bach`. 

However, I was able to get custom hooks work through through the `withProps` enhancer from the `bach-recompose` library. Is this the correct way to include custom hooks? Could you please add an example to the documentation?

Here is an [example](https://codesandbox.io/s/cocky-wave-81ur4?file=/src/App.tsx)

**Comment by jgretz** [comment]
please see https://bach.truefit.io/docs/bach-withhook/
