### ISSUE TITLE
Unmet peer dependency when installing with (classic) yarn

### ISSUE THREAD

**Issue by robations** [TrueFit/bach#16]
Hi, I'm checking this out as an alternative to recompose, good to see the baton being passed on.

```
warning " > @truefit/bach@2.0.9" has unmet peer dependency "react@^16.x".
warning " > @truefit/bach-recompose@2.0.6" has unmet peer dependency "react@^16.x".
```

Shouldn't that be expressed as `"react@^16"`? Or I think it could be `"react@16.x"`? Either way, I have a version of react 16 installed as a direct dependency and still getting this warning.

**Comment by jgretz** [comment]
sorry for the delay - I have published 2.0.10 which updates the peer dependency definition to "16.x"
