### ISSUE TITLE
composing composed enhancers

### ISSUE THREAD

**Issue by tim-crisp** [TrueFit/bach#8]
Hi, I'm getting an issue when composing composed enhancers:

```javascript
import { compose, withState } from "@truefit/bach";
import { renameProp } from "@truefit/bach-recompose";

const withOtherComposedEnchancers = compose(
  withState("bob", "setOriginalBob"),
  renameProp("bob", "originalBob")
);

const EnhancedComponent = compose(
  withState("bob", "setBob"),
  withOtherComposedEnchancers
);

export default function App() {
  return <EnhancedComponent />;
}
```

You can see the full stack trace in this [code sandbox](https://codesandbox.io/s/xenodochial-clarke-2ef1x).

Is it intentional that you can't compose composed enhancers?

Thanks!

**Comment by jgretz** [comment]
Compose returns a component not an enhancer. There are a couple of issues with your code calling the library that are causing the issues you are seeing, but they both come down to not passing a component to wrap. The compose function is curried function - it's first call takes the enhancers, and returns a function that takes the root component. 

In your example, you first need a root component that will render, then secondly need to pass the withOtherComposedEnhancers as a component not and enhancer. See below:

```
import React from "react";
import { compose, withState } from "@truefit/bach";
import { renameProp } from "@truefit/bach-recompose";

const Component = ({ originalBob }) => <div>Hello {originalBob}</div>;

const withOtherComposedEnchancers = compose(
  withState("bob", "setOriginalBob", "Bob"),
  renameProp("bob", "originalBob")
)(Component);

const EnhancedComponent = compose(withState("bob", "setBob"))(
  withOtherComposedEnchancers
);

export default function App() {
  return <EnhancedComponent />;
}
```

**Comment by tim-crisp** [comment]
Thanks for getting back to me @jgretz. Apologies for missing out the actual component as part of the snippet I posted 🤦‍♂, thankfully you were able to see past my stupidity. That explanation has cleared things up, thanks a lot for taking the time to answer 👍
