### ISSUE TITLE
[Suggestion] Composing Composers

### ISSUE THREAD

**Issue by tim-crisp** [TrueFit/bach#9]
Hi,

I created an issue a few days ago in relation to having the ability to combine multiple composed enhancers into a single composition. Apologies if the jargon I've used is slightly off. This is the solution I've found and that I'm going to be using as a temporary solution in my apps:

```javascript
import React from "react";
import {
  compose as originalCompose,
  withState,
  withEffect
} from "@truefit/bach";

const flattenEnhancers = tree =>
  tree
    .map(compositionOrEnhancer => [
      compositionOrEnhancer.enhancers
        ? flattenEnhancers(compositionOrEnhancer.enhancers)
        : compositionOrEnhancer
    ])
    .flat(Infinity);

const compose = (...args) => {
  const fn = originalCompose(...flattenEnhancers(args));
  fn.enhancers = args;
  return fn;
};

const firstComposition = compose(
  withState("firstCount", "setFirstCount", 100),
  withState("secondCount", "setSecondCount", 0)
);

const secondComposition = compose(
  firstComposition,
  withState("name", "setName", "Bob")
);

const thirdComposition = compose(
  secondComposition,
  withEffect(({ setFirstCount }) => setFirstCount(50), [])
);

const ComponentWithAllEnhancers = thirdComposition(
  ({ firstCount, secondCount, setFirstCount, setSecondCount, name }) => (
    <div>
      <div>{name}</div>
      <div onClick={() => setFirstCount(++firstCount)}>{firstCount}</div>
      <div onClick={() => setSecondCount(--secondCount)}>{secondCount}</div>
    </div>
  )
);
```

As you can see, I've introduced an `enhancers` property on the function returned by `compose`. This enables you to recursively go through all the enhancers and build up a single array of enhancers to provide to the root compose. I personally found it very powerful to be able to combine a set of composed HOC's in recompose. If you feel that this is a viable solution, I'll be happy to create a PR at some point.

Please feel free to fork the [code sandbox](https://codesandbox.io/s/xenodochial-clarke-2ef1x) and have a play.

Thanks!

**Comment by jgretz** [comment]
I'm not sure I like the syntax of adding a property to the function. I would actually prefer to see this as a secondary compose function - something like composeEnhancers(...enhancers).

That said, I'm not sure I see the use case for this - is it reusability? If you wouldn't mind expanding on the  higher level context of when you would use this approach, perhaps I could see it better.

Thanks

**Comment by tim-crisp** [comment]
I was also a bit sceptical about adding a property to the function to be honest, but I can't see any other way of achieving it. The composeEnhancers suggestion seems good, however I'm not sure how this would work since you'll still have the issue of not being able to combine several composed enhancers.

The use case is reusability, it might be easier if I just provide real world example. I'm currently having to implement internationalisation in one of the applications I'm working with. I decided it would be appropriate to have a HOC/Enhancers to modularise this functionality so that multiple components can reuse it. It looks something like this:

```javascript
const withTranslator = compose(
  withSelector('translationState', ({ translator }) => translator),
  withCallback('t', ({ translationState }) => (textToTranslate) => translationState[textToTranslate], ['translationState'])
);
```
There is a bit more functionality to it than what the snippet shows, but you get the idea. There is some translation state in the redux store and this higher order component is responsible for ensuring that all components enhanced by it adhere to the current set of translations in the store.

Alongside internationalisation there is a requirement to have dynamic configuration to drive certain aspects of component functionality (i.e. the max value for a numerical input). Again, this is functionality that can be modularised and reused across the entire application, so it seems ideal to put it into a HOC/Enhancers. The config HOC might look like this:

```javascript
const withConfig = configurationOptions => compose(
  withSelector('configState', ({ config }) => config),
  // use configuration options to inject config from store as props into component
)
```

Now lets assume that we have some component that needs to use both of these sets of enhancers. Its much nicer to have one composition statement to combine the functionality of the two than it is to call the first composition with a component, and then proceed to pass the result into the second composition. If that statement doesn't make sense, its essentially what you showed me in #8 

Personally I find the following snippet easier to read:
```javascript
const enhance = compose(
  withConfig(/* object containing what config should be mapped to what props */),
  withTranslator
);

const EnhancedComponent = enhance(Component);
```

Than the following snippet:
```javascript
const EnhancedComponent = withTranslator(
  withConfig(/* object containing what config should be mapped to what props */)(Component)
);
```

The first `enhance` could also be reused if it was needed, whereas the second snippet is bound to the component. It's also worth noting that the more higher order components you want to enhance a component with, the messier it gets. Being able to compose them gives you a clear view of what functionality a component is being enhanced with.

Let me know if thats any clearer. If not, I can create a code sandbox with some examples.

Thanks!

**Comment by jgretz** [comment]
I've added an exported function composeEnhancers and updated the signature of compose to support your example above.

the one small change is using composeEnhancers to create those reusable enhancer "groups".

so using your example code:

```Javascript
const withTranslator = composeEnhancers(
  withSelector('translationState', ({ translator }) => translator),
  withCallback('t', ({ translationState }) => (textToTranslate) => translationState[textToTranslate], ['translationState'])
);

const withConfig = configurationOptions => composeEnhancers(
  withSelector('configState', ({ config }) => config),
  // use configuration options to inject config from store as props into component
);

const enhance = compose(
  withConfig(/* object containing what config should be mapped to what props */),
  withTranslator
);

const EnhancedComponent = enhance(Component);
```
